server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;  # Cambiado
        index html/index.html;        # Apunta al archivo index.html
        try_files $uri /html/$uri /html/index.html =404;  # Intenta acceder a los archivos en /html y, si no, carga index.html
    }

    location /css/ {
        alias /usr/share/nginx/html/css/;  # Usando alias para evitar problemas de ruta
    }

    location /js/ {
        alias /usr/share/nginx/html/js/;  # Usando alias para acceder a los archivos js
    }
}

